#eureka server服务端口
server:
  port: 9998
  servlet:
    context-path: /
security:
  oauth2:
    client:
      client-id: client_1
      client-secret: abcxyz
      access-token-uri: http://localhost:9999/oauth/token
      user-authorization-uri: http://localhost:9999/oauth/authorize
    resource:
      token-info-uri: http://localhost:9999/oauth/check_token
spring:
  application:
    name: cloud-oauth-server-9998 # 应用名称，应用名称会在Eureka中作为服务名称
  thymeleaf:
    cache: false #关闭页面缓存
    prefix: classpath:/public/ #thymeleaf访问根路径
    mode: LEGACYHTML5
  cloud:
    inetutils:
      # 指定此客户端的ip
      default-ip-address: springcloud

#eureka配置
eureka:
  instance:
    hostname: springcloud  # 当前eureka实例的主机名
    ip-address: springcloud
  client:
    service-url:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30
      # 租约到期，服务时效时间，默认值90秒,服务超过90秒没有发??跳，服务注册中心会将服务从列表移除
      lease-expiration-duration-in-seconds: 90
      # 配置客户端所交互的Eureka Server的地址（Eureka Server集群中每一个Server其实相对于其它Server来说都是Client）
      # 集群模式下，defaultZone应该指向其它Eureka Server，如果有更多其它Server实例，逗号拼接即可
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka # 注册到集群汇总，多个用,拼接
    register-with-eureka: true  # 集群模式下可以改成true
    fetch-registry: true # 集群模式下可以改成true